In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score, f1_score, recall_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
from sklearn.decomposition import KernelPCA
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import xgboost as xgb
from sklearn.svm import SVC, SVR
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder

In [4]:
datos = pd.read_csv('datos_procesados.csv')
landmarks = datos.drop(columns='label')
labels = datos['label']

In [8]:
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)

xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=5, gamma = 0.1, max_depth = 5, n_estimators = 500)
xgb_model.fit(X_train, y_train)
param_grid = {
    "learning_rate": [0.01, 0.1, 0.3, 0.5],
    "n_estimators": [100, 500, 1000],
    "gamma": [0, 0.1, 0.3, 0.5],
    'max_depth': [5, 10, 15],
}

# Realizar la búsqueda de hiperparámetros
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1)
grid_search.fit(X_train, y_train)

# Mostrar los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", grid_search.best_params_)

Fitting 3 folds for each of 144 candidates, totalling 432 fits


c:\Users\camic\OneDrive\Documentos\Inteligencia artificial\ProjectIA\venv\Lib\site-packages\numpy\ma\core.py:2881: RuntimeWarning: invalid value encountered in cast
  _data = np.array(data, dtype=dtype, copy=copy,


Mejores hiperparámetros: {'gamma': 0, 'learning_rate': 0.01, 'max_depth': 5, 'n_estimators': 1000}


In [5]:
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)

xgb_model = xgb.XGBClassifier(objective='multi:softmax',gamma= 0, learning_rate= 0.01, max_depth= 5, n_estimators= 1000)
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

In [6]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Exactitud del modelo:", accuracy)
print("\nMatriz de Confusión:\n", conf_matrix)
print("\nReporte de Clasificación:\n", class_report)

Exactitud del modelo: 0.9989683631361761

Matriz de Confusión:
 [[ 272    0    0    0    0]
 [   0 1339    0    0    0]
 [   0    1  293    0    0]
 [   0    0    2  503    0]
 [   0    0    0    0  498]]

Reporte de Clasificación:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00       272
           1       1.00      1.00      1.00      1339
           2       0.99      1.00      0.99       294
           3       1.00      1.00      1.00       505
           4       1.00      1.00      1.00       498

    accuracy                           1.00      2908
   macro avg       1.00      1.00      1.00      2908
weighted avg       1.00      1.00      1.00      2908



In [7]:
label_encoder.inverse_transform([0, 1, 2, 3, 4])

array(["['siting_down']", "['spinning']", "['standing_up']",
       "['walking_away']", "['walking_to_camera']"], dtype=object)

In [8]:
X = StandardScaler().fit_transform(landmarks)
pca = PCA(n_components=17) # Reduce to 2 dimensions for visualization  # Reduce to 2 dimensions for visualization
new_x = pca.fit_transform(X)

scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(new_x, numeric_labels, test_size=0.3, random_state=42)

xgb_model = xgb.XGBClassifier(objective='multi:softmax',gamma= 0, learning_rate= 0.01, max_depth= 5, n_estimators= 1000)
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

In [9]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Exactitud del modelo:", accuracy)
print("\nMatriz de Confusión:\n", conf_matrix)
print("\nReporte de Clasificación:\n", class_report)

Exactitud del modelo: 0.7936726272352133

Matriz de Confusión:
 [[ 160  101    3    0    8]
 [   6 1289    5   17   22]
 [   2   81  197    8    6]
 [   5  148    3  334   15]
 [   0  140    3   27  328]]

Reporte de Clasificación:
               precision    recall  f1-score   support

           0       0.92      0.59      0.72       272
           1       0.73      0.96      0.83      1339
           2       0.93      0.67      0.78       294
           3       0.87      0.66      0.75       505
           4       0.87      0.66      0.75       498

    accuracy                           0.79      2908
   macro avg       0.86      0.71      0.77      2908
weighted avg       0.82      0.79      0.79      2908

