In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score, f1_score, recall_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
from sklearn.decomposition import KernelPCA
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import xgboost as xgb
from sklearn.svm import SVC, SVR
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
import pickle
from sklearn.svm import SVC


In [4]:
datos = pd.read_csv('datos_procesados.csv')
landmarks = datos.drop(columns='230')
labels = datos['230']

In [5]:
landmarks = landmarks.drop(columns=['Unnamed: 0'])

In [18]:
import warnings

warnings.filterwarnings('ignore')
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)



param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto', 0.001, 0.01, 0.1, 1],
    #'degree': [2, 3, 4]  # Solo se usará si kernel='poly'
}

#Realizar la búsqueda de hiperparámetros
grid_search = GridSearchCV(estimator=SVC(), param_grid=param_grid, scoring='accuracy', cv=5, n_jobs=-1)
grid_search.fit(X_train, y_train)

#Mostrar los mejores hiperparámetros encontrados
print("Mejores hiperparámetros sacarosa:", grid_search.best_params)

AttributeError: 'GridSearchCV' object has no attribute 'best_params'

In [68]:
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)

xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=5, gamma = 0.1, max_depth = 5, n_estimators = 500)
xgb_model.fit(X_train, y_train)
param_grid = {
    "learning_rate": [0.01, 0.1, 0.3, 0.5],
    "n_estimators": [100, 500, 1000],
    "gamma": [0, 0.1, 0.3, 0.5],
    'max_depth': [5, 10, 15],
}

# Realizar la búsqueda de hiperparámetros
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1)
grid_search.fit(X_train, y_train)

# Mostrar los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", grid_search.best_params_)

KeyboardInterrupt: 

In [ ]:
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)

xgb_model = SVC(gamma= 'scale', C= 1, kernel='rbf')
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

In [17]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Exactitud del modelo:", accuracy)
print("\nMatriz de Confusión:\n", conf_matrix)
print("\nReporte de Clasificación:\n", class_report)

Exactitud del modelo: 0.690748898678414

Matriz de Confusión:
 [[ 106  228   14    2    4]
 [  13 1383    6   25   19]
 [  22  194  132    7    4]
 [   5  312    4  296   45]
 [   0  141    1    7  435]]

Reporte de Clasificación:
               precision    recall  f1-score   support

           0       0.73      0.30      0.42       354
           1       0.61      0.96      0.75      1446
           2       0.84      0.37      0.51       359
           3       0.88      0.45      0.59       662
           4       0.86      0.74      0.80       584

    accuracy                           0.69      3405
   macro avg       0.78      0.56      0.61      3405
weighted avg       0.74      0.69      0.67      3405



In [71]:
import joblib

# Save the model to a file
joblib_file = "xgb_model.pkl"
joblib.dump(xgb_model, joblib_file)

print(f"Model saved to {joblib_file}")

Model saved to xgb_model.pkl


In [72]:
# Save the scaler to a file
with open('scaler.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)

In [22]:
label_encoder.inverse_transform([0, 1, 2, 3, 4])

array(["['siting_down']", "['spinning']", "['standing_up']",
       "['walking_away']", "['walking_to_camera']"], dtype=object)

In [27]:
X = StandardScaler().fit_transform(landmarks)
pca = PCA(n_components=28) # Reduce to 2 dimensions for visualization  # Reduce to 2 dimensions for visualization
new_x = pca.fit_transform(X)

scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(new_x, numeric_labels, test_size=0.3, random_state=42)

xgb_model = xgb.XGBClassifier(objective='multi:softmax',gamma= 0, learning_rate= 0.01, max_depth= 5, n_estimators= 1000)
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

In [28]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Exactitud del modelo:", accuracy)
print("\nMatriz de Confusión:\n", conf_matrix)
print("\nReporte de Clasificación:\n", class_report)

Exactitud del modelo: 0.870388507998694

Matriz de Confusión:
 [[ 219   59   24    3    0]
 [   9 1318   13   14   17]
 [  13   52  232   11    1]
 [   6  124    8  409    8]
 [   0   25    7    3  488]]

Reporte de Clasificación:
               precision    recall  f1-score   support

           0       0.89      0.72      0.79       305
           1       0.84      0.96      0.89      1371
           2       0.82      0.75      0.78       309
           3       0.93      0.74      0.82       555
           4       0.95      0.93      0.94       523

    accuracy                           0.87      3063
   macro avg       0.88      0.82      0.85      3063
weighted avg       0.88      0.87      0.87      3063

