In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error, accuracy_score, f1_score, recall_score, confusion_matrix, classification_report
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
import numpy as np
from sklearn.decomposition import KernelPCA
from sklearn.linear_model import LogisticRegression
import matplotlib.pyplot as plt
import seaborn as sns
import datetime as dt
import xgboost as xgb
from sklearn.svm import SVC, SVR
from sklearn.model_selection import GridSearchCV
from sklearn.preprocessing import LabelEncoder
import pickle
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier


In [2]:
datos = pd.read_csv('datos_procesados.csv')
landmarks = datos.drop(columns='230')
labels = datos['230']

In [3]:
landmarks = landmarks.drop(columns=['Unnamed: 0'])

In [10]:
import warnings

warnings.filterwarnings('ignore')
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)



param_grid = {
    'C': [0.1, 1, 10, 100],
    'kernel': ['linear', 'rbf', 'poly'],
    'gamma': ['scale', 'auto', 0.001, 0.01, 0.1, 1],
    #'degree': [2, 3, 4]  # Solo se usará si kernel='poly'
}

#Realizar la búsqueda de hiperparámetros
grid_search = GridSearchCV(estimator=SVC(), param_grid=param_grid, scoring='accuracy', cv=5, n_jobs=-1)
grid_search.fit(X_train, y_train)

#Mostrar los mejores hiperparámetros encontrados
print("Mejores hiperparámetros sacarosa:", grid_search.best_params_)

Mejores hiperparámetros sacarosa: {'C': 100, 'gamma': 0.01, 'kernel': 'rbf'}


In [68]:
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)

xgb_model = xgb.XGBClassifier(objective='multi:softmax', num_class=5, gamma = 0.1, max_depth = 5, n_estimators = 500)
xgb_model.fit(X_train, y_train)
param_grid = {
    "learning_rate": [0.01, 0.1, 0.3, 0.5],
    "n_estimators": [100, 500, 1000],
    "gamma": [0, 0.1, 0.3, 0.5],
    'max_depth': [5, 10, 15],
}

# Realizar la búsqueda de hiperparámetros
grid_search = GridSearchCV(estimator=xgb_model, param_grid=param_grid, scoring='accuracy', cv=3, verbose=1)
grid_search.fit(X_train, y_train)

# Mostrar los mejores hiperparámetros encontrados
print("Mejores hiperparámetros:", grid_search.best_params_)

KeyboardInterrupt: 

In [4]:
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)
# Define the parameter grid for Random Forest
param_grid_rf = {
    'n_estimators': [100, 200, 300],
    'max_depth': [None, 10, 20, 30],
    'min_samples_split': [2, 5, 10],
    'min_samples_leaf': [1, 2, 4],
    'bootstrap': [True, False]
}

# Initialize the Random Forest Classifier
rf_model = RandomForestClassifier(random_state=42)

# Perform GridSearchCV
grid_search_rf = GridSearchCV(estimator=rf_model, param_grid=param_grid_rf, scoring='accuracy', cv=3, n_jobs=-1, verbose=1)
grid_search_rf.fit(X_train, y_train)

# Display the best parameters
print("Best parameters for Random Forest:", grid_search_rf.best_params_)

Fitting 3 folds for each of 216 candidates, totalling 648 fits


KeyboardInterrupt: 

In [5]:
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)

xgb_model = RandomForestClassifier(bootstrap= False, max_depth= 20, min_samples_leaf= 1, min_samples_split= 2, n_estimators= 300)
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

In [11]:
scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(scaler.fit_transform(landmarks), numeric_labels, test_size=0.3, random_state=42)

xgb_model = SVC(gamma= 0.01, C= 100, kernel='rbf')
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

In [6]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Exactitud del modelo:", accuracy)
print("\nMatriz de Confusión:\n", conf_matrix)
print("\nReporte de Clasificación:\n", class_report)

Exactitud del modelo: 0.9785609397944199

Matriz de Confusión:
 [[ 339    6    6    1    2]
 [   3 1433    2    5    3]
 [  15    3  338    2    1]
 [   3    5    0  652    2]
 [   0   10    2    2  570]]

Reporte de Clasificación:
               precision    recall  f1-score   support

           0       0.94      0.96      0.95       354
           1       0.98      0.99      0.99      1446
           2       0.97      0.94      0.96       359
           3       0.98      0.98      0.98       662
           4       0.99      0.98      0.98       584

    accuracy                           0.98      3405
   macro avg       0.97      0.97      0.97      3405
weighted avg       0.98      0.98      0.98      3405



In [7]:
import joblib

# Save the model to a file
joblib_file = "xgb_model.pkl"
joblib.dump(xgb_model, joblib_file)

print(f"Model saved to {joblib_file}")

Model saved to xgb_model.pkl


In [8]:
# Save the scaler to a file
with open('scaler.pkl', 'wb') as scaler_file:
    pickle.dump(scaler, scaler_file)

In [22]:
label_encoder.inverse_transform([0, 1, 2, 3, 4])

array(["['siting_down']", "['spinning']", "['standing_up']",
       "['walking_away']", "['walking_to_camera']"], dtype=object)

In [27]:
X = StandardScaler().fit_transform(landmarks)
pca = PCA(n_components=28) # Reduce to 2 dimensions for visualization  # Reduce to 2 dimensions for visualization
new_x = pca.fit_transform(X)

scaler = StandardScaler()
label_encoder = LabelEncoder()
numeric_labels = label_encoder.fit_transform(labels)
X_train, X_test, y_train, y_test = train_test_split(new_x, numeric_labels, test_size=0.3, random_state=42)

xgb_model = xgb.XGBClassifier(objective='multi:softmax',gamma= 0, learning_rate= 0.01, max_depth= 5, n_estimators= 1000)
xgb_model.fit(X_train, y_train)

y_pred = xgb_model.predict(X_test)

In [28]:
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print("Exactitud del modelo:", accuracy)
print("\nMatriz de Confusión:\n", conf_matrix)
print("\nReporte de Clasificación:\n", class_report)

Exactitud del modelo: 0.870388507998694

Matriz de Confusión:
 [[ 219   59   24    3    0]
 [   9 1318   13   14   17]
 [  13   52  232   11    1]
 [   6  124    8  409    8]
 [   0   25    7    3  488]]

Reporte de Clasificación:
               precision    recall  f1-score   support

           0       0.89      0.72      0.79       305
           1       0.84      0.96      0.89      1371
           2       0.82      0.75      0.78       309
           3       0.93      0.74      0.82       555
           4       0.95      0.93      0.94       523

    accuracy                           0.87      3063
   macro avg       0.88      0.82      0.85      3063
weighted avg       0.88      0.87      0.87      3063

